services:
  mongodb:
    image: mongo
    container_name: meeting-namoo-db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - data:/data/db
    networks:
      - meeting-net
  fastapi:
    image: seokjunh/namoo-meeting:back-latest
    container_name: meeting-namoo-back
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - meeting-net
  react:
    image: seokjunh/namoo-meeting:front-latest
    container_name: meeting-namoo-front
    restart: always
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: meeting.namooinc.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: meeting.namooinc.com
      LETSENCRYPT_EMAIL: admin@namooinc.com
    depends_on:
      - fastapi
    networks:
      - meeting-net
      - proxy

volumes:
  data:

networks:
  meeting-net:
  proxy:
    external: true
