services:
  fastapi:
    image: seokjunh/namoo-meeting:back-latest
    container_name: meeting-namoo-back
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: ${MONGO_URL}
    networks:
      - meeting-net
      - fastapi-mongo-net
  react:
    image: seokjunh/namoo-meeting:front-latest
    container_name: meeting-namoo-front
    restart: always
    environment:
      VIRTUAL_HOST: meeting.namooinc.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: meeting.namooinc.com
      LETSENCRYPT_EMAIL: admin@namooinc.com
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - fastapi
    networks:
      - meeting-net
      - proxy

networks:
  meeting-net:
  fastapi-mongo-net:
    external: true
  proxy:
    external: true
