services:
  mongodb:
    image: mongo
    container_name: meeting-namoo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - data:/data/db
    networks:
      - fastapi-mongo-net

volumes:
  data:

networks:
  fastapi-mongo-net:
    external: true