/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmallRoomRouteImport } from './routes/small-room'
import { Route as LargeRoomRouteImport } from './routes/large-room'
import { Route as IndexRouteImport } from './routes/index'

const SmallRoomRoute = SmallRoomRouteImport.update({
  id: '/small-room',
  path: '/small-room',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeRoomRoute = LargeRoomRouteImport.update({
  id: '/large-room',
  path: '/large-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/large-room': typeof LargeRoomRoute
  '/small-room': typeof SmallRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/large-room': typeof LargeRoomRoute
  '/small-room': typeof SmallRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/large-room': typeof LargeRoomRoute
  '/small-room': typeof SmallRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/large-room' | '/small-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/large-room' | '/small-room'
  id: '__root__' | '/' | '/large-room' | '/small-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LargeRoomRoute: typeof LargeRoomRoute
  SmallRoomRoute: typeof SmallRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/small-room': {
      id: '/small-room'
      path: '/small-room'
      fullPath: '/small-room'
      preLoaderRoute: typeof SmallRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/large-room': {
      id: '/large-room'
      path: '/large-room'
      fullPath: '/large-room'
      preLoaderRoute: typeof LargeRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LargeRoomRoute: LargeRoomRoute,
  SmallRoomRoute: SmallRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
