name: Deploy MongoDB

on:
  workflow_dispatch: # 수동 실행
  push:
    paths:
      - ".github/workflows/deploy-mongodb.yml" #deploy-mongodb.yml이 변경되면 실행

jobs:
  deploy-mongo:
    runs-on: ubuntu-latest
    env:
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Ensure MongoDB directory exists
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          script: |
            mkdir -p /namooinc/db/mongodb

      - name: Copy MongoDB Compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          source: "./mongodb/docker-compose.yml"
          target: "/namooinc/db/mongodb/"

      - name: Run MongoDB Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          envs: MONGO_USERNAME,MONGO_PASSWORD,MONGO_DATABASE
          script: |
            set -e
            cd /namooinc/db/mongodb
            docker compose up -d
